- name: Setup Database Server

  hosts: db_servers
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
    - name: ping
      ping:
  roles:
    - python
    - database

- name: Setup Web Servers
  hosts: web_servers
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
    - name: ping
      ping:
  roles:
    - python
    - flask